services:
  # Unified server for embeddings
  embeddings-server:
    build:
      context: .
      dockerfile: ./Docker/unified-server/Dockerfile
    image: fake-openai-server/unified-server:latest
    environment:
      - SERVICE_TYPE=embeddings
    ports:
      - 8081:8081/tcp
    volumes:
      - ./volumes/hf-cache:/opt/fos/.cache/huggingface
    networks:
      - fos-net
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  # Unified server for reranker
  reranker-server:
    build:
      context: .
      dockerfile: ./Docker/unified-server/Dockerfile
    image: fake-openai-server/unified-server:latest
    environment:
      - SERVICE_TYPE=reranker
    ports:
      - 8082:8082/tcp
    volumes:
      - ./volumes/hf-cache:/opt/fos/.cache/huggingface
    networks:
      - fos-net
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

networks:
  fos-net:
