services:
  base-server:
    build:
      context: .
      dockerfile: ./Docker/base-server/Dockerfile
    image: fake-openai-server/base-server:latest
    volumes:
      - ./volumes/hf-cache:/opt/fos/.cache/huggingface
    networks:
      - fos-net

  reranker-server:
    build:
      context: .
      dockerfile: ./Docker/reranker-server/Dockerfile
    image: fake-openai-server/reranker-server:latest
    ports:
      - 8082:8082/tcp
    volumes:
      - ./volumes/hf-cache:/opt/fos/.cache/huggingface
    networks:
      - fos-net
    depends_on:
      base-server:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

networks:
  fos-net:
