name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      # GitHub Container Registryへログイン
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      # fake-openai-serverイメージをビルドしてpush
      - name: Build fake-openai-server image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/fake-openai-server:latest -f Docker/reranker-server/Dockerfile .

      - name: Push fake-openai-server image
        run: docker push ghcr.io/${{ github.repository_owner }}/fake-openai-server:latest
